### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by bbashy** [Casinelli/Laravel-CampaignMonitor#3]
Can you bump the version to the latest for https://github.com/campaignmonitor/createsend-php ?

v5 seems to have been fixed for this error I'm getting;

```
[ErrorException]
  Methods with the same name as their class will not be constructors in a future version of PHP; CS_REST_Subscribers has a deprecated constructor
```

**Comment by Casinelli** [comment]
Bumped. Let me know if it works now.

**Comment by bbashy** [comment]
Works, thanks!
